id: weather_pipeline
name: weather_pipeline
config:
  root_dir: $EXAMPLE_ROOT/weather_pipeline
  params:
    enable_cache: true
  source:
    config:
      local_file:
        path: $EXAMPLE_ROOT/data
  sink:
    config:
      empty:
        empty: true
  metadata:
    sqlite:
      path: $EXAMPLE_ROOT/metadata
  steps:
    - pipeline_path: $EXAMPLE_ROOT/pipelines/partition.yaml
    - pipeline_path: $EXAMPLE_ROOT/pipelines/train.yaml
