id: weather_pipeline
name: weather_pipeline
config:
  root_dir: $EXAMPLE_ROOT/weather_pipeline
  params:
    enable_cache: true
  source:
    config:
      local_file:
        path: $EXAMPLE_ROOT/data
  sink:
    config:
      empty:
        empty: true
  metadata:
    sqlite:
      path: $EXAMPLE_ROOT/metadata
  stages:
    - id: '0'
      name: CsvExampleGen
      config:
        csv_example_gen:
          inputs:
            input: pipeline.source.channel
          outputs:
            examples: examples
    - id: '1'
      name: StatisticsGen
      config:
        statistics_gen:
          inputs:
            examples: 0.outputs.examples
          outputs:
            statistics: statistics
    - id: '2'
      name: SchemaGen
      config:
        schema_gen:
          inputs:
            statistics: 1.outputs.statistics
          params:
            infer_feature_shape: false
          outputs:
            schema: schema
    - id: '3'
      name: Transform
      config:
        transform:
          inputs:
            examples: 0.outputs.examples
            schema: 2.outputs.schema
          params:
            module_file: $EXAMPLE_ROOT/module/introduce_timestamp.py
          outputs:
            transformed_examples: examples
    - id: '4'
      name: StatisticsGen
      config:
        statistics_gen:
          inputs:
            examples: 3.outputs.examples
          outputs:
            statistics: statistics
    - id: '5'
      name: SchemaGen
      config:
        schema_gen:
          inputs:
            statistics: 4.outputs.statistics
          params:
            infer_feature_shape: false
          outputs:
            schema: schema
    - id: '6'
      name: ExampleValidator
      config:
        example_validator:
          inputs:
            statistics: 4.outputs.statistics
            schema: 5.outputs.schema
          outputs:
            anomalies: anomalies
    - id: '7'
      name: Transform
      config:
        transform:
          inputs:
            examples: 3.outputs.examples
            schema: 5.outputs.schema
          params:
            module_file: $EXAMPLE_ROOT/module/normalize.py
          outputs:
            transformed_examples: examples
            transform_graph: graph
    - id: '8'
      name: Trainer
      config:
        trainer:
          inputs:
            schema: 5.outputs.schema
            examples: 7.outputs.examples
            transform_graph: 7.outputs.graph
          params:
            module_file: $EXAMPLE_ROOT/module/trainer.py
            train_args:
              num_steps: 500
            eval_args:
              num_steps: 500
          outputs:
            model: model
