id: weather_pipeline
name: weather_pipeline
config:
  root_dir: $EXAMPLE_ROOT/weather_pipeline
  params:
    enable_cache: true
  inputs:
   - source:
       id: data
       config:
         local_file:
           path: $EXAMPLE_ROOT/data
  metadata:
    sqlite:
      path: $EXAMPLE_ROOT/metadata
  steps:
    - sequence_path: $EXAMPLE_ROOT/pipelines/ingest.yaml
    - sequence_path: $EXAMPLE_ROOT/pipelines/normalize.yaml
    - sequence_path: $EXAMPLE_ROOT/pipelines/train.yaml
