# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hilo_rpc/proto/logging.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hilo_rpc/proto/logging.proto',
  package='hilo_rpc.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1chilo_rpc/proto/logging.proto\x12\x0ehilo_rpc.proto\"0\n\rLoggingConfig\x12\r\n\x05level\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\tb\x06proto3'
)




_LOGGINGCONFIG = _descriptor.Descriptor(
  name='LoggingConfig',
  full_name='hilo_rpc.proto.LoggingConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='hilo_rpc.proto.LoggingConfig.level', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='hilo_rpc.proto.LoggingConfig.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['LoggingConfig'] = _LOGGINGCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoggingConfig = _reflection.GeneratedProtocolMessageType('LoggingConfig', (_message.Message,), {
  'DESCRIPTOR' : _LOGGINGCONFIG,
  '__module__' : 'hilo_rpc.proto.logging_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.LoggingConfig)
  })
_sym_db.RegisterMessage(LoggingConfig)


# @@protoc_insertion_point(module_scope)
