# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hilo_rpc/proto/metadata.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hilo_rpc.proto import storage_pb2 as hilo__rpc_dot_proto_dot_storage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hilo_rpc/proto/metadata.proto',
  package='hilo_rpc.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1dhilo_rpc/proto/metadata.proto\x12\x0ehilo_rpc.proto\x1a\x1chilo_rpc/proto/storage.proto\"O\n\x13MetadataStoreConfig\x12.\n\x06sqlite\x18\x01 \x01(\x0b\x32\x1c.hilo_rpc.proto.SqliteConfigH\x00\x42\x08\n\x06\x63onfigb\x06proto3'
  ,
  dependencies=[hilo__rpc_dot_proto_dot_storage__pb2.DESCRIPTOR,])




_METADATASTORECONFIG = _descriptor.Descriptor(
  name='MetadataStoreConfig',
  full_name='hilo_rpc.proto.MetadataStoreConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sqlite', full_name='hilo_rpc.proto.MetadataStoreConfig.sqlite', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='config', full_name='hilo_rpc.proto.MetadataStoreConfig.config',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=79,
  serialized_end=158,
)

_METADATASTORECONFIG.fields_by_name['sqlite'].message_type = hilo__rpc_dot_proto_dot_storage__pb2._SQLITECONFIG
_METADATASTORECONFIG.oneofs_by_name['config'].fields.append(
  _METADATASTORECONFIG.fields_by_name['sqlite'])
_METADATASTORECONFIG.fields_by_name['sqlite'].containing_oneof = _METADATASTORECONFIG.oneofs_by_name['config']
DESCRIPTOR.message_types_by_name['MetadataStoreConfig'] = _METADATASTORECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetadataStoreConfig = _reflection.GeneratedProtocolMessageType('MetadataStoreConfig', (_message.Message,), {
  'DESCRIPTOR' : _METADATASTORECONFIG,
  '__module__' : 'hilo_rpc.proto.metadata_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.MetadataStoreConfig)
  })
_sym_db.RegisterMessage(MetadataStoreConfig)


# @@protoc_insertion_point(module_scope)
