# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hilo_rpc/proto/partition.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow_metadata.proto.v0 import schema_pb2 as tensorflow__metadata_dot_proto_dot_v0_dot_schema__pb2
from tensorflow_metadata.proto.v0 import statistics_pb2 as tensorflow__metadata_dot_proto_dot_v0_dot_statistics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hilo_rpc/proto/partition.proto',
  package='hilo_rpc.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1ehilo_rpc/proto/partition.proto\x12\x0ehilo_rpc.proto\x1a)tensorflow_metadata/proto/v0/schema.proto\x1a-tensorflow_metadata/proto/v0/statistics.proto\"*\n\x0c\x45xampleSplit\x12\r\n\x05split\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\"\xc9\x01\n\tPartition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x06schema\x18\x03 \x01(\x0b\x32\x1e.tensorflow.metadata.v0.Schema\x12H\n\nstatistics\x18\x02 \x01(\x0b\x32\x34.tensorflow.metadata.v0.DatasetFeatureStatisticsList\x12\x34\n\x0e\x65xample_splits\x18\x04 \x03(\x0b\x32\x1c.hilo_rpc.proto.ExampleSplit\">\n\rPartitionList\x12-\n\npartitions\x18\x01 \x03(\x0b\x32\x19.hilo_rpc.proto.Partitionb\x06proto3'
  ,
  dependencies=[tensorflow__metadata_dot_proto_dot_v0_dot_schema__pb2.DESCRIPTOR,tensorflow__metadata_dot_proto_dot_v0_dot_statistics__pb2.DESCRIPTOR,])




_EXAMPLESPLIT = _descriptor.Descriptor(
  name='ExampleSplit',
  full_name='hilo_rpc.proto.ExampleSplit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='split', full_name='hilo_rpc.proto.ExampleSplit.split', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='hilo_rpc.proto.ExampleSplit.uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=182,
)


_PARTITION = _descriptor.Descriptor(
  name='Partition',
  full_name='hilo_rpc.proto.Partition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hilo_rpc.proto.Partition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='hilo_rpc.proto.Partition.schema', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statistics', full_name='hilo_rpc.proto.Partition.statistics', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='example_splits', full_name='hilo_rpc.proto.Partition.example_splits', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=386,
)


_PARTITIONLIST = _descriptor.Descriptor(
  name='PartitionList',
  full_name='hilo_rpc.proto.PartitionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partitions', full_name='hilo_rpc.proto.PartitionList.partitions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=450,
)

_PARTITION.fields_by_name['schema'].message_type = tensorflow__metadata_dot_proto_dot_v0_dot_schema__pb2._SCHEMA
_PARTITION.fields_by_name['statistics'].message_type = tensorflow__metadata_dot_proto_dot_v0_dot_statistics__pb2._DATASETFEATURESTATISTICSLIST
_PARTITION.fields_by_name['example_splits'].message_type = _EXAMPLESPLIT
_PARTITIONLIST.fields_by_name['partitions'].message_type = _PARTITION
DESCRIPTOR.message_types_by_name['ExampleSplit'] = _EXAMPLESPLIT
DESCRIPTOR.message_types_by_name['Partition'] = _PARTITION
DESCRIPTOR.message_types_by_name['PartitionList'] = _PARTITIONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleSplit = _reflection.GeneratedProtocolMessageType('ExampleSplit', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLESPLIT,
  '__module__' : 'hilo_rpc.proto.partition_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.ExampleSplit)
  })
_sym_db.RegisterMessage(ExampleSplit)

Partition = _reflection.GeneratedProtocolMessageType('Partition', (_message.Message,), {
  'DESCRIPTOR' : _PARTITION,
  '__module__' : 'hilo_rpc.proto.partition_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.Partition)
  })
_sym_db.RegisterMessage(Partition)

PartitionList = _reflection.GeneratedProtocolMessageType('PartitionList', (_message.Message,), {
  'DESCRIPTOR' : _PARTITIONLIST,
  '__module__' : 'hilo_rpc.proto.partition_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.PartitionList)
  })
_sym_db.RegisterMessage(PartitionList)


# @@protoc_insertion_point(module_scope)
