# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hilo_rpc/proto/runner.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hilo_rpc/proto/runner.proto',
  package='hilo_rpc.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1bhilo_rpc/proto/runner.proto\x12\x0ehilo_rpc.proto\"0\n\x13\x42\x65\x61mDagRunnerConfig\x12\x19\n\x11orchestrator_args\x18\x01 \x03(\t\"M\n\x0cRunnerConfig\x12\x33\n\x04\x62\x65\x61m\x18\x01 \x01(\x0b\x32#.hilo_rpc.proto.BeamDagRunnerConfigH\x00\x42\x08\n\x06\x63onfigb\x06proto3'
)




_BEAMDAGRUNNERCONFIG = _descriptor.Descriptor(
  name='BeamDagRunnerConfig',
  full_name='hilo_rpc.proto.BeamDagRunnerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orchestrator_args', full_name='hilo_rpc.proto.BeamDagRunnerConfig.orchestrator_args', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=95,
)


_RUNNERCONFIG = _descriptor.Descriptor(
  name='RunnerConfig',
  full_name='hilo_rpc.proto.RunnerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beam', full_name='hilo_rpc.proto.RunnerConfig.beam', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='config', full_name='hilo_rpc.proto.RunnerConfig.config',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=97,
  serialized_end=174,
)

_RUNNERCONFIG.fields_by_name['beam'].message_type = _BEAMDAGRUNNERCONFIG
_RUNNERCONFIG.oneofs_by_name['config'].fields.append(
  _RUNNERCONFIG.fields_by_name['beam'])
_RUNNERCONFIG.fields_by_name['beam'].containing_oneof = _RUNNERCONFIG.oneofs_by_name['config']
DESCRIPTOR.message_types_by_name['BeamDagRunnerConfig'] = _BEAMDAGRUNNERCONFIG
DESCRIPTOR.message_types_by_name['RunnerConfig'] = _RUNNERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BeamDagRunnerConfig = _reflection.GeneratedProtocolMessageType('BeamDagRunnerConfig', (_message.Message,), {
  'DESCRIPTOR' : _BEAMDAGRUNNERCONFIG,
  '__module__' : 'hilo_rpc.proto.runner_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.BeamDagRunnerConfig)
  })
_sym_db.RegisterMessage(BeamDagRunnerConfig)

RunnerConfig = _reflection.GeneratedProtocolMessageType('RunnerConfig', (_message.Message,), {
  'DESCRIPTOR' : _RUNNERCONFIG,
  '__module__' : 'hilo_rpc.proto.runner_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.RunnerConfig)
  })
_sym_db.RegisterMessage(RunnerConfig)


# @@protoc_insertion_point(module_scope)
