# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hilo_rpc/proto/sink.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from hilo_rpc.proto import connector_pb2 as hilo__rpc_dot_proto_dot_connector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hilo_rpc/proto/sink.proto',
  package='hilo_rpc.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x19hilo_rpc/proto/sink.proto\x12\x0ehilo_rpc.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ehilo_rpc/proto/connector.proto\"u\n\nSinkConfig\x12,\n\x05\x65mpty\x18\x01 \x01(\x0b\x32\x1b.hilo_rpc.proto.EmptyConfigH\x00\x12/\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x1f.hilo_rpc.proto.LocalFileConfigH\x00\x42\x08\n\x06\x63onfig\"\xc1\x01\n\x04Sink\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x06\x63onfig\x18\x06 \x01(\x0b\x32\x1a.hilo_rpc.proto.SinkConfig\"6\n\x11\x43reateSinkRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\" \n\x12\x43reateSinkResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\x11\x44\x65leteSinkRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12\x44\x65leteSinkResponse\"\x1c\n\x0eGetSinkRequest\x12\n\n\x02id\x18\x01 \x01(\t\"5\n\x0fGetSinkResponse\x12\"\n\x04Sink\x18\x01 \x01(\x0b\x32\x14.hilo_rpc.proto.Sink2\xff\x01\n\x07SinkApi\x12S\n\nCreateSink\x12!.hilo_rpc.proto.CreateSinkRequest\x1a\".hilo_rpc.proto.CreateSinkResponse\x12S\n\nDeleteSink\x12!.hilo_rpc.proto.DeleteSinkRequest\x1a\".hilo_rpc.proto.DeleteSinkResponse\x12J\n\x07GetSink\x12\x1e.hilo_rpc.proto.GetSinkRequest\x1a\x1f.hilo_rpc.proto.GetSinkResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,hilo__rpc_dot_proto_dot_connector__pb2.DESCRIPTOR,])




_SINKCONFIG = _descriptor.Descriptor(
  name='SinkConfig',
  full_name='hilo_rpc.proto.SinkConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='empty', full_name='hilo_rpc.proto.SinkConfig.empty', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='hilo_rpc.proto.SinkConfig.file', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='config', full_name='hilo_rpc.proto.SinkConfig.config',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=110,
  serialized_end=227,
)


_SINK = _descriptor.Descriptor(
  name='Sink',
  full_name='hilo_rpc.proto.Sink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hilo_rpc.proto.Sink.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='hilo_rpc.proto.Sink.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='hilo_rpc.proto.Sink.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='hilo_rpc.proto.Sink.created_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='hilo_rpc.proto.Sink.updated_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='hilo_rpc.proto.Sink.config', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=423,
)


_CREATESINKREQUEST = _descriptor.Descriptor(
  name='CreateSinkRequest',
  full_name='hilo_rpc.proto.CreateSinkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hilo_rpc.proto.CreateSinkRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='hilo_rpc.proto.CreateSinkRequest.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=479,
)


_CREATESINKRESPONSE = _descriptor.Descriptor(
  name='CreateSinkResponse',
  full_name='hilo_rpc.proto.CreateSinkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hilo_rpc.proto.CreateSinkResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=513,
)


_DELETESINKREQUEST = _descriptor.Descriptor(
  name='DeleteSinkRequest',
  full_name='hilo_rpc.proto.DeleteSinkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hilo_rpc.proto.DeleteSinkRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=546,
)


_DELETESINKRESPONSE = _descriptor.Descriptor(
  name='DeleteSinkResponse',
  full_name='hilo_rpc.proto.DeleteSinkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=568,
)


_GETSINKREQUEST = _descriptor.Descriptor(
  name='GetSinkRequest',
  full_name='hilo_rpc.proto.GetSinkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hilo_rpc.proto.GetSinkRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=598,
)


_GETSINKRESPONSE = _descriptor.Descriptor(
  name='GetSinkResponse',
  full_name='hilo_rpc.proto.GetSinkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Sink', full_name='hilo_rpc.proto.GetSinkResponse.Sink', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=653,
)

_SINKCONFIG.fields_by_name['empty'].message_type = hilo__rpc_dot_proto_dot_connector__pb2._EMPTYCONFIG
_SINKCONFIG.fields_by_name['file'].message_type = hilo__rpc_dot_proto_dot_connector__pb2._LOCALFILECONFIG
_SINKCONFIG.oneofs_by_name['config'].fields.append(
  _SINKCONFIG.fields_by_name['empty'])
_SINKCONFIG.fields_by_name['empty'].containing_oneof = _SINKCONFIG.oneofs_by_name['config']
_SINKCONFIG.oneofs_by_name['config'].fields.append(
  _SINKCONFIG.fields_by_name['file'])
_SINKCONFIG.fields_by_name['file'].containing_oneof = _SINKCONFIG.oneofs_by_name['config']
_SINK.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SINK.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SINK.fields_by_name['config'].message_type = _SINKCONFIG
_GETSINKRESPONSE.fields_by_name['Sink'].message_type = _SINK
DESCRIPTOR.message_types_by_name['SinkConfig'] = _SINKCONFIG
DESCRIPTOR.message_types_by_name['Sink'] = _SINK
DESCRIPTOR.message_types_by_name['CreateSinkRequest'] = _CREATESINKREQUEST
DESCRIPTOR.message_types_by_name['CreateSinkResponse'] = _CREATESINKRESPONSE
DESCRIPTOR.message_types_by_name['DeleteSinkRequest'] = _DELETESINKREQUEST
DESCRIPTOR.message_types_by_name['DeleteSinkResponse'] = _DELETESINKRESPONSE
DESCRIPTOR.message_types_by_name['GetSinkRequest'] = _GETSINKREQUEST
DESCRIPTOR.message_types_by_name['GetSinkResponse'] = _GETSINKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SinkConfig = _reflection.GeneratedProtocolMessageType('SinkConfig', (_message.Message,), {
  'DESCRIPTOR' : _SINKCONFIG,
  '__module__' : 'hilo_rpc.proto.sink_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.SinkConfig)
  })
_sym_db.RegisterMessage(SinkConfig)

Sink = _reflection.GeneratedProtocolMessageType('Sink', (_message.Message,), {
  'DESCRIPTOR' : _SINK,
  '__module__' : 'hilo_rpc.proto.sink_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.Sink)
  })
_sym_db.RegisterMessage(Sink)

CreateSinkRequest = _reflection.GeneratedProtocolMessageType('CreateSinkRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESINKREQUEST,
  '__module__' : 'hilo_rpc.proto.sink_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.CreateSinkRequest)
  })
_sym_db.RegisterMessage(CreateSinkRequest)

CreateSinkResponse = _reflection.GeneratedProtocolMessageType('CreateSinkResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESINKRESPONSE,
  '__module__' : 'hilo_rpc.proto.sink_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.CreateSinkResponse)
  })
_sym_db.RegisterMessage(CreateSinkResponse)

DeleteSinkRequest = _reflection.GeneratedProtocolMessageType('DeleteSinkRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESINKREQUEST,
  '__module__' : 'hilo_rpc.proto.sink_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.DeleteSinkRequest)
  })
_sym_db.RegisterMessage(DeleteSinkRequest)

DeleteSinkResponse = _reflection.GeneratedProtocolMessageType('DeleteSinkResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETESINKRESPONSE,
  '__module__' : 'hilo_rpc.proto.sink_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.DeleteSinkResponse)
  })
_sym_db.RegisterMessage(DeleteSinkResponse)

GetSinkRequest = _reflection.GeneratedProtocolMessageType('GetSinkRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSINKREQUEST,
  '__module__' : 'hilo_rpc.proto.sink_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.GetSinkRequest)
  })
_sym_db.RegisterMessage(GetSinkRequest)

GetSinkResponse = _reflection.GeneratedProtocolMessageType('GetSinkResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSINKRESPONSE,
  '__module__' : 'hilo_rpc.proto.sink_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.GetSinkResponse)
  })
_sym_db.RegisterMessage(GetSinkResponse)



_SINKAPI = _descriptor.ServiceDescriptor(
  name='SinkApi',
  full_name='hilo_rpc.proto.SinkApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=656,
  serialized_end=911,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSink',
    full_name='hilo_rpc.proto.SinkApi.CreateSink',
    index=0,
    containing_service=None,
    input_type=_CREATESINKREQUEST,
    output_type=_CREATESINKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteSink',
    full_name='hilo_rpc.proto.SinkApi.DeleteSink',
    index=1,
    containing_service=None,
    input_type=_DELETESINKREQUEST,
    output_type=_DELETESINKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSink',
    full_name='hilo_rpc.proto.SinkApi.GetSink',
    index=2,
    containing_service=None,
    input_type=_GETSINKREQUEST,
    output_type=_GETSINKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SINKAPI)

DESCRIPTOR.services_by_name['SinkApi'] = _SINKAPI

# @@protoc_insertion_point(module_scope)
