# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from hilo_rpc.proto import sink_pb2 as hilo__rpc_dot_proto_dot_sink__pb2


class SinkApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateSink = channel.unary_unary(
        '/hilo_rpc.proto.SinkApi/CreateSink',
        request_serializer=hilo__rpc_dot_proto_dot_sink__pb2.CreateSinkRequest.SerializeToString,
        response_deserializer=hilo__rpc_dot_proto_dot_sink__pb2.CreateSinkResponse.FromString,
        )
    self.DeleteSink = channel.unary_unary(
        '/hilo_rpc.proto.SinkApi/DeleteSink',
        request_serializer=hilo__rpc_dot_proto_dot_sink__pb2.DeleteSinkRequest.SerializeToString,
        response_deserializer=hilo__rpc_dot_proto_dot_sink__pb2.DeleteSinkResponse.FromString,
        )
    self.GetSink = channel.unary_unary(
        '/hilo_rpc.proto.SinkApi/GetSink',
        request_serializer=hilo__rpc_dot_proto_dot_sink__pb2.GetSinkRequest.SerializeToString,
        response_deserializer=hilo__rpc_dot_proto_dot_sink__pb2.GetSinkResponse.FromString,
        )


class SinkApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateSink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SinkApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateSink': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSink,
          request_deserializer=hilo__rpc_dot_proto_dot_sink__pb2.CreateSinkRequest.FromString,
          response_serializer=hilo__rpc_dot_proto_dot_sink__pb2.CreateSinkResponse.SerializeToString,
      ),
      'DeleteSink': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSink,
          request_deserializer=hilo__rpc_dot_proto_dot_sink__pb2.DeleteSinkRequest.FromString,
          response_serializer=hilo__rpc_dot_proto_dot_sink__pb2.DeleteSinkResponse.SerializeToString,
      ),
      'GetSink': grpc.unary_unary_rpc_method_handler(
          servicer.GetSink,
          request_deserializer=hilo__rpc_dot_proto_dot_sink__pb2.GetSinkRequest.FromString,
          response_serializer=hilo__rpc_dot_proto_dot_sink__pb2.GetSinkResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hilo_rpc.proto.SinkApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
