# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hilo_rpc/proto/source.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from hilo_rpc.proto import connector_pb2 as hilo__rpc_dot_proto_dot_connector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hilo_rpc/proto/source.proto',
  package='hilo_rpc.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1bhilo_rpc/proto/source.proto\x12\x0ehilo_rpc.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ehilo_rpc/proto/connector.proto\"O\n\x0cSourceConfig\x12\x35\n\nlocal_file\x18\x01 \x01(\x0b\x32\x1f.hilo_rpc.proto.LocalFileConfigH\x00\x42\x08\n\x06\x63onfig\"\xd4\x01\n\x06Source\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05owner\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x06\x63onfig\x18\x07 \x01(\x0b\x32\x1c.hilo_rpc.proto.SourceConfigb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,hilo__rpc_dot_proto_dot_connector__pb2.DESCRIPTOR,])




_SOURCECONFIG = _descriptor.Descriptor(
  name='SourceConfig',
  full_name='hilo_rpc.proto.SourceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_file', full_name='hilo_rpc.proto.SourceConfig.local_file', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='config', full_name='hilo_rpc.proto.SourceConfig.config',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=112,
  serialized_end=191,
)


_SOURCE = _descriptor.Descriptor(
  name='Source',
  full_name='hilo_rpc.proto.Source',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hilo_rpc.proto.Source.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='hilo_rpc.proto.Source.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='hilo_rpc.proto.Source.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='hilo_rpc.proto.Source.owner', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='hilo_rpc.proto.Source.created_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='hilo_rpc.proto.Source.updated_at', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='hilo_rpc.proto.Source.config', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=406,
)

_SOURCECONFIG.fields_by_name['local_file'].message_type = hilo__rpc_dot_proto_dot_connector__pb2._LOCALFILECONFIG
_SOURCECONFIG.oneofs_by_name['config'].fields.append(
  _SOURCECONFIG.fields_by_name['local_file'])
_SOURCECONFIG.fields_by_name['local_file'].containing_oneof = _SOURCECONFIG.oneofs_by_name['config']
_SOURCE.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SOURCE.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SOURCE.fields_by_name['config'].message_type = _SOURCECONFIG
DESCRIPTOR.message_types_by_name['SourceConfig'] = _SOURCECONFIG
DESCRIPTOR.message_types_by_name['Source'] = _SOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SourceConfig = _reflection.GeneratedProtocolMessageType('SourceConfig', (_message.Message,), {
  'DESCRIPTOR' : _SOURCECONFIG,
  '__module__' : 'hilo_rpc.proto.source_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.SourceConfig)
  })
_sym_db.RegisterMessage(SourceConfig)

Source = _reflection.GeneratedProtocolMessageType('Source', (_message.Message,), {
  'DESCRIPTOR' : _SOURCE,
  '__module__' : 'hilo_rpc.proto.source_pb2'
  # @@protoc_insertion_point(class_scope:hilo_rpc.proto.Source)
  })
_sym_db.RegisterMessage(Source)


# @@protoc_insertion_point(module_scope)
