id: train
config:
  inputs:
    - channel:
        id: schema
        url: sequence/normalize/outputs/schema
    - channel:
        id: transformed_graph
        url: sequence/normalize/outputs/transformed_graph
    - channel:
        id: examples
        url: sequence/normalize/outputs/examples
  steps:
    - stage:
        id: '0'
        name: Trainer
        config:
          trainer:
            inputs:
              schema: inputs/schema
              examples: inputs/examples
              transform_graph: inputs/transformed_graph
            params:
              module_file: $EXAMPLE_ROOT/module/trainer.py
              train_args:
                num_steps: 500
              eval_args:
                num_steps: 500
            outputs:
              model: model
    - stage:
        id: '1'
        name: ModelResolver
        config:
          resolver_node:
            outputs:
              model: model
    - stage:
        id: '2'
        name: ModelEvaluator
        config:
          evaluator:
            inputs:
              examples: inputs/examples
              model: stages/0/outputs/model
              baseline_model: stages/1/outputs/model
            outputs:
              blessing: blessing
    - stage:
        id: '3'
        name: ModelPusher
        config:
          pusher:
            inputs:
              model: stages/0/outputs/model
              model_blessing: stages/2/outputs/blessing
              push_destination:
                filesystem:
                  $EXAMPLE_ROOT/weather-model
